version: '3'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: prisma
    ports:
      - 5430:5430
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: {}
